import { Parser } from "binary-parser";

export const CreatePlayer = new Parser()
  .endianness("little")
  .uint32("to")
  .uint32("player")
  .uint32("group")
  .uint32("packedPlayerOffset")
  .uint32("passwordOffset")
  .uint32("playerSize")
  .uint32("flags")
  .uint32("packedPlayerId")
  .uint32("packedPlayerShortNameLength")
  .uint32("packedPlayerLongNameLength")
  .uint32("packedPlayerServiceProviderSize")
  .uint32("packedPlayerDataSize")
  .uint32("packedPlayerCount")
  .uint32("packedPlayerSystemId")
  .uint32("packedPlayerFixedSize")
  .uint32("packedPlayerDialect")
  .uint32("packedPlayerUnknown1")
  .string("packedPlayerShortName", {length: "packedPlayerShortNameLength", stripNull: true})
  .buffer("packedPlayerServiceProvider", {length: "packedPlayerServiceProviderSize"})
  ;